### Word Embedding Techniques using Embedding Layer in Keras

In [2]:
##tensorflow >2.0
from tensorflow.keras.preprocessing.text import one_hot

In [3]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [4]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [5]:
### Vocabulary size
voc_size=10000

### One Hot Representation

In [6]:
onehot_repr=[one_hot(words,voc_size)for words in sent] 
print(onehot_repr)

[[2544, 2191, 4391, 3314], [2544, 2191, 4391, 2067], [2544, 5228, 4391, 3667], [6329, 3725, 5291, 5278, 8741], [6329, 3725, 5291, 5278, 2232], [1072, 2544, 1261, 4391, 5250], [75, 3712, 9293, 5278]]


### Word Embedding Represntation

In [7]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [8]:
import numpy as np

In [9]:
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 2544 2191 4391 3314]
 [   0    0    0    0 2544 2191 4391 2067]
 [   0    0    0    0 2544 5228 4391 3667]
 [   0    0    0 6329 3725 5291 5278 8741]
 [   0    0    0 6329 3725 5291 5278 2232]
 [   0    0    0 1072 2544 1261 4391 5250]
 [   0    0    0    0   75 3712 9293 5278]]


In [10]:
dim=10

In [11]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

In [12]:
model.summary()


Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 8, 10)             100000    
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [13]:

print(model.predict(embedded_docs))

[[[ 0.02918639 -0.01765292 -0.0406569   0.04730394  0.02896718
   -0.04650304 -0.00654707 -0.04613155  0.04834073 -0.04816839]
  [ 0.02918639 -0.01765292 -0.0406569   0.04730394  0.02896718
   -0.04650304 -0.00654707 -0.04613155  0.04834073 -0.04816839]
  [ 0.02918639 -0.01765292 -0.0406569   0.04730394  0.02896718
   -0.04650304 -0.00654707 -0.04613155  0.04834073 -0.04816839]
  [ 0.02918639 -0.01765292 -0.0406569   0.04730394  0.02896718
   -0.04650304 -0.00654707 -0.04613155  0.04834073 -0.04816839]
  [-0.0125159   0.04138645  0.04452017 -0.03119898  0.03369099
   -0.02202621  0.01928831  0.0358131  -0.00965381  0.00073468]
  [-0.04186409 -0.02682593 -0.0273706   0.00979277 -0.03474236
   -0.00301754  0.00829725  0.03235774  0.01474893 -0.00643003]
  [ 0.04149386  0.03609017 -0.03134847  0.01074594 -0.04427933
   -0.04902002 -0.01764225 -0.02206076  0.04783406 -0.0242161 ]
  [-0.04739055 -0.0125914   0.02955523  0.04245115 -0.02759196
    0.03723821  0.00497548 -0.00494682  0.013930

In [14]:
embedded_docs[0]

array([   0,    0,    0,    0, 2544, 2191, 4391, 3314])

In [15]:
print(model.predict(embedded_docs)[0])

[[ 0.02918639 -0.01765292 -0.0406569   0.04730394  0.02896718 -0.04650304
  -0.00654707 -0.04613155  0.04834073 -0.04816839]
 [ 0.02918639 -0.01765292 -0.0406569   0.04730394  0.02896718 -0.04650304
  -0.00654707 -0.04613155  0.04834073 -0.04816839]
 [ 0.02918639 -0.01765292 -0.0406569   0.04730394  0.02896718 -0.04650304
  -0.00654707 -0.04613155  0.04834073 -0.04816839]
 [ 0.02918639 -0.01765292 -0.0406569   0.04730394  0.02896718 -0.04650304
  -0.00654707 -0.04613155  0.04834073 -0.04816839]
 [-0.0125159   0.04138645  0.04452017 -0.03119898  0.03369099 -0.02202621
   0.01928831  0.0358131  -0.00965381  0.00073468]
 [-0.04186409 -0.02682593 -0.0273706   0.00979277 -0.03474236 -0.00301754
   0.00829725  0.03235774  0.01474893 -0.00643003]
 [ 0.04149386  0.03609017 -0.03134847  0.01074594 -0.04427933 -0.04902002
  -0.01764225 -0.02206076  0.04783406 -0.0242161 ]
 [-0.04739055 -0.0125914   0.02955523  0.04245115 -0.02759196  0.03723821
   0.00497548 -0.00494682  0.01393027  0.01807627]]